"""add Department

Revision ID: 39284d0d0fd4
Revises: ff30444e3e52
Create Date: 2024-04-10 01:31:50.643275

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '39284d0d0fd4'
down_revision = 'ff30444e3e52'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('department',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('address', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('department')
    # ### end Alembic commands ###
