"""rename department

Revision ID: 86169c441271
Revises: 39284d0d0fd4
Create Date: 2024-04-10 01:39:40.025529

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '86169c441271'
down_revision = '39284d0d0fd4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('departments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('address', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    #This is done when you rename or change something on the models, this is done before we upgrade()
    op.rename_table('department', 'departments')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('department',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=False),
    sa.Column('address', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    #This is done when you rename or change something on the models, this is done before we upgrade()
    op.rename_table('departments', 'department')
    # ### end Alembic commands ###
