"""rename location

Revision ID: 8a369411fb8f
Revises: 0e96e57893a4
Create Date: 2024-04-10 02:03:11.882890

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a369411fb8f'
down_revision = '0e96e57893a4'
branch_labels = None
depends_on = None



def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('departments', 'location',  new_column_name='locations')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('departments', 'location',  new_column_name='locations')
    # ### end Alembic commands ###